### PR TITLE
#291: Adjustments for linux resolver

### LINKED ISSUE #291: [bug] Incorrect resolver file for Ubuntu 20
**Describe the bug**
Pygmy-go assumes that all linux systems utilize `/etc/resolv.conf` for managing custom DNS resolvers. On Ubuntu 20, that file is not considered, and will be overwritten by Network Manager without warning. Custom resolvers can be placed in `/etc/systemd/resolved.conf.d` instead. Instead of injecting the single line into `/etc/resolv.conf`, Pygmy-go should create `/etc/systemd/resolved.conf.d/docker.amazee.io.conf` with the following contents

```
[Resolve]
DNS=127.0.0.1:6053
Domains=docker.amazee.io
```

### PR DESCRIPTION
**Pull request by fubarhouse**
In the example of Debian and Debian-based systems the Linux resolver does not work.

In testing on Arch, the new configuration works in the exact same way with the added benefit of the configuration structured exactly like the mac one - one configuration file per resolver.

This one resolves #291

### CODE REVIEW

File: service/library/setup.go [hunk 1]
```diff
@@ -89,11 +89,11 @@ func Setup(c *Config) {
 			Name:    "MacOS Resolver",
 		}
 
-		var ResolvGeneric = resolv.Resolv{
-			Data:    "nameserver 127.0.0.1 # added by amazee.io pygmy",
+		var ResolvLinux = resolv.Resolv{
+			Data:    "# Generated by amazeeio pygmy\n[Resolve]\nDNS=127.0.0.1:6053\nDomains=docker.amazee.io",
```
Comment (twardnw) [inline service/library/setup.go]: Could we newline at the end?

**Comment by twardnw** [comment]
I was able to test on Ubuntu 20.04, this works as expected

**Comment by tobybellwood** [comment]
agreed, LGTM

nice work!

File: service/library/setup.go (hunk 1 above)
Comment (fubarhouse) [reply service/library/setup.go]: Resolved in 9bdcaeeda54d013c06e8539358dce4fb0c219499
